apiVersion: v1
kind: Service
metadata:
  labels:
    app: dark-spin-rollout
  name: svc-rollout
  namespace: spinnaker-operator
spec:
  ports:
    - port: 8090
      protocol: TCP
      targetPort: 8090
  selector:
    app: dark-spin-rollout
status:
  loadBalancer: {}
